services:
  db:
    image: postgres:9.6.23
    restart: always
    networks:
      - network
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data

networks:
  network:
